### ISSUE TITLE
Change Motrix UI port with a environment variable

### ISSUE THREAD

**Issue by rohoal1012** [Jarvay/Motrix-Web#2]
I want to change the motrix port to the port 80 but i cant because i dont use bridge network on docker, i use ipvlan network mode so i cant change the forward port on the compose, so pleaseee a option to change the motrix port directlyyyy 🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by Jarvay** [comment]
You can use env `WEB_UI_PORT` to set it now.
