### ISSUE TITLE
你好 docker-compose up -d之后是否还需要其它操作 我添加下载链接后提示 Failed to fetch

### ISSUE THREAD

**Issue by MonsoXv** [Jarvay/Motrix-Web#3]
### Bug 描述

添加下载链接后提示 Failed to fetch

### Motrix 版本

添加下载链接后提示 Failed to fetch

### 环境

无

### 复现步骤

无

### 额外信息

无

### 验证

- [X] 遵循我们的[行为准则](https：//github.com/agalwood/Motrix/blob/master/CODE_OF_CONDUCT.md)
- [X] 确认是否已经有一个报告了相同的 Bug，以避免创建重复的问题。
- [X] 确认此问题是一个具体的 Bug。若要进行问答，请开启 [GitHub 讨论](https://github.com/agalwood/Motrix/discussions)。
- [X] 提供的复现是该 Bug 的 [最小复现例子](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Jarvay** [comment]
是所有下载链接都是这样吗，还是只有个别会这样，方便的话提供下截图
