### ISSUE TITLE
[BUG]: 下载时提示 Load failed

### ISSUE THREAD

**Issue by firedevel** [Jarvay/Motrix-Web#4]
### Bug 描述

添加任务，然后提示Load failed

### Motrix 版本

/

### 环境

/

### 复现步骤

点击 添加任务

### 验证

- [X] 遵循我们的[行为准则](https：//github.com/agalwood/Motrix/blob/master/CODE_OF_CONDUCT.md)
- [X] 确认是否已经有一个报告了相同的 Bug，以避免创建重复的问题。
- [X] 确认此问题是一个具体的 Bug。若要进行问答，请开启 [GitHub 讨论](https://github.com/agalwood/Motrix/discussions)。
- [X] 提供的复现是该 Bug 的 [最小复现例子](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by firedevel** [comment]
![IMG_7576](https://github.com/user-attachments/assets/76177fe6-d93a-4e9d-949a-aadf0fef7ce7)

**Comment by Jarvay** [comment]
所有下载链接都是这样吗，如果所有都是这样看看aria2的设置有没有问题

**Comment by firedevel** [comment]
所有都是，aria2-pro就是按照readme配置的，应该没有问题

**Comment by Jarvay** [comment]
设置-进阶设置-RPC Host 有设置成相应地址吗
